### PR TITLE
Added LUKS2 support

### PR DESCRIPTION
**Pull request by skim-milk**
Added LUKS2 support with a luksVersion (-v) flag.

### CODE REVIEW

**Comment by derektamsen** [comment]
@skim-milk thanks for adding support for LUKS2. I really appreciate it. Before I can merge the PR though I will need to take a look and get the tests working again, but have not had a lot of time recently. I think it may have something to do with the circleci image not having support for luks2.

**Comment by skim-milk** [comment]
It wasn't succeeding with `go test` (from memory) either, and I couldn't figure out why. No worries on the eta for review/merge, we needed it and I figured I'd PR it back. luks2crypt is super cool. 😎

**Comment by derektamsen** [comment]
I figured out why the tests are failing. It needs some more refining to support backwards compatibility though.

In `internal/luks/luks_test.go` the `testDisk` struct needs the luks version added:

```
type testDisk struct {
	path, pass, newPass string
	size                int64
	luksVersion         int
}
```

Then, in any of the `luks_test.go` calls to `testDisk{}` the `luksVersion` should be specified. The final part is adjusting `format()` in `internal/luks/luks.go` in a backwards compatible way. When formatting a luks2 devices it looks like the last two parameters need to be updated. [Example usage in the cryptsetup repo](https://gitlab.com/cryptsetup/cryptsetup/-/blob/master/docs/examples/crypt_luks_usage.c#L67-68):

```
cFormatRes := C.crypt_format(
		luksDevice.cDevice,
		cLuksType,
		cLuksCipher,
		cLuksCipherMode,
		nil,
		nil,
		C.ulong(512/8),
		nil,
	)
```

**Comment by skim-milk** [comment]
Oh, awesome. I'll get to this tonight or over the weekend if you don't beat
me to it 😬

**Comment by skim-milk** [comment]
The above changes pass the currently defined tests (only LUKS, not LUKS2).
I really just added `LuksVersion` in a bunch of places 😬

**Comment by derektamsen** [comment]
@skim-milk the tests are passing. I am going to merge this PR to get luks2 support added. Feel free to open a new PR if you want to update the tests for luks2 as well. Thanks for you help!

**Pull request merged**
