### PR TITLE
Add basic auth

### PR DESCRIPTION
**Pull request by sheagcraig**
Per @weswhet request, I added basic auth flags.

### CODE REVIEW

**Comment by sheagcraig** [comment]
I'm very much a go n00b, so help me out here ;)

**Comment by derektamsen** [comment]
@sheagcraig This is great! Thanks for opening the PR.

**Comment by weswhet** [comment]
Thanks for having a look @derektamsen!

**Comment by derektamsen** [comment]
This has been released as [v0.3.0](https://github.com/square/luks2crypt/releases/tag/v0.3.0)

**Pull request merged**
